version: '3.9'
services:
  mongodb:
    image: mongo:7
    container_name: startup_portal_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: startup_portal_backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: startup_portal_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
